name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deployment:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from Production Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ap-southeast-1

      - name: Build zip
        run: |
          mkdir lambda_package
          docker run --rm -v $(pwd)/lambda_package:/lambda_package -w /lambda_package amazonlinux:2023 /bin/bash -c "yum install -y python3 pip && pip3 install --target=/lambda_package fastapi boto3 mangum pydantic"
          cp app.py lambda_package/
          cp lambda.py lambda_package/
          cd lambda_package
          zip -r ../pyesa_api_lambda.zip .

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Initialize
        id: init
        working-directory: ./infra
        run: |
          terraform init -backend-config=aws.conf

      - name: Terraform Validate
        id: validate
        working-directory: ./infra
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        working-directory: ./infra
        run: terraform apply --auto-approve
        env:
          TF_VAR_region: ${{ vars.S3_AWS_REGION }}
          TF_VAR_S3_BUCKET: ${{ vars.MASS_FILES }}
          TF_VAR_MASS_FILES: ${{ vars.MASS_FILES }}

